### ISSUE TITLE
Gulp default task hangs

### ISSUE THREAD

**Issue by kennethlynne** [strongloop/loopback-example-pubsub#3] opened 2015-08-03 11:01 UTC
It does not quit

**Comment by superkhau** [comment] 2015-08-18 21:54
Confirmed. Would you like to submit a patch?

**Comment by superkhau** [comment] 2016-02-03 02:18
@0candy Reassigning to you since you are the repo expert.

**Comment by pktippa** [comment] 2016-02-20 08:05
We can close this issue since the pull #14 is accepted and merged.

**Comment by 0candy** [comment] 2016-04-01 21:01
Fixed merged, closing this issue.

**Closed by 0candy** 2016-04-01 21:01 UTC
Labels: bug
